# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Arc < Formula
  desc "A.R.C. Framework CLI - Agent Runtime Core for managing and orchestrating AI infrastructure"
  homepage "https://github.com/arc-framework/arc-cli"
  version "0.2.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arc-framework/arc-cli/releases/download/v0.2.7/arc-cli_darwin_amd64.tar.gz"
      sha256 "48d2612ff1c1819511025b929640e6ae28df05189fdbcc9d033ec8f3086e72bc"

      define_method(:install) do
        bin.install "arc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arc-framework/arc-cli/releases/download/v0.2.7/arc-cli_darwin_arm64.tar.gz"
      sha256 "4c017d9cdc6e85da3f9ad1c1eb605d262065b7ebbb560c4803cb854b7ef57ab5"

      define_method(:install) do
        bin.install "arc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arc-framework/arc-cli/releases/download/v0.2.7/arc-cli_linux_amd64.tar.gz"
      sha256 "6a20d16ce0225544763c0c00fd03db1eec6f6378444161fe22a899ecf38407d1"
      define_method(:install) do
        bin.install "arc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arc-framework/arc-cli/releases/download/v0.2.7/arc-cli_linux_arm64.tar.gz"
      sha256 "2cd1be716c43208342ee918b3763214961e5532935e6139d79b02649096ae9bf"
      define_method(:install) do
        bin.install "arc"
      end
    end
  end

  test do
    system "#{bin}/arc", "version"
  end
end
